---
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Table Football
description: Learn how to make a world cup football game in Scratch!
original_url: https://codeclubprojects.org/en-GB/scratch/table-football
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: Get the pitch ready for a game
- title: Add a goalie
- title: Add some more players
- title: Add some attacking players
- title: Add a bouncing ball
- title: Kicking the ball
- title: GOOOOOOAAAAAALLLLLLLLL!!!!!!!!

